cp ../../../2_MoSe2/SZVnonaug/bandstructure_SCF_and_G0W0* SZV-MOLOPT/
cp ../../../2_MoSe2/SZVnonaug/GW.inp SZV-MOLOPT/
cp ../../../2_MoSe2/SZVnonaug/cp2k.out SZV-MOLOPT/
cp ../../../2_MoSe2/DZVPnonaug/1e-3/bandstructure_SCF_and_G0W0* DZVP-MOLOPT/
cp ../../../2_MoSe2/DZVPnonaug/1e-3/GW.inp DZVP-MOLOPT/
cp ../../../2_MoSe2/DZVPnonaug/1e-3/cp2k.out DZVP-MOLOPT/
cp ../../../2_MoSe2/TZVPnonaug/1e-3/bandstructure_SCF_and_G0W0* TZVP-MOLOPT/
cp ../../../2_MoSe2/TZVPnonaug/1e-3/GW.inp* TZVP-MOLOPT/
cp ../../../2_MoSe2/TZVPnonaug/1e-3/cp2k.out* TZVP-MOLOPT/
cp ../../../2_MoSe2/TZV2Pnonaug/1e-3/bandstructure_SCF_and_G0W0* TZV2P-MOLOPT/
cp ../../../2_MoSe2/TZV2Pnonaug/1e-3/GW.inp* TZV2P-MOLOPT/
cp ../../../2_MoSe2/TZV2Pnonaug/1e-3/cp2k.out* TZV2P-MOLOPT/
cp ../../../2_MoSe2/SZV/1e-3/cp2k.out aug-SZV-MOLOPT/
cp ../../../2_MoSe2/SZV/1e-3/GW.inp aug-SZV-MOLOPT/
cp ../../../2_MoSe2/SZV/1e-3/bandstructure_SCF_and_G0W0* aug-SZV-MOLOPT/
cp ../../../2_MoSe2/TZVP/1e-3/cp2k.out aug-TZVP-MOLOPT/
cp ../../../2_MoSe2/TZVP/1e-3/GW.inp aug-TZVP-MOLOPT/
cp ../../../2_MoSe2/TZVP/1e-3/bandstructure_SCF_and_G0W0* aug-TZVP-MOLOPT/
